### PR TITLE
add gebak

### PR DESCRIPTION
**Pull request by lubdeptrai**

### CODE REVIEW

**Comment by lubdeptrai** [comment]
Hi keithyong
Why it wasn't added to the soundboard page? :(

**Comment by paoyong** [comment]
@lubdeptrai Ill make sure its on the website, let me check the code!

**Comment by lubdeptrai** [comment]
thanks for great work bro xD

**Comment by paoyong** [comment]
Alright your changes are on the main website now :)

**Comment by lubdeptrai** [comment]
Thanks Keith,
But the "everyone gebak" doesn't work... pls check bro :(

**Pull request merged**
